podinfo:
  replicaCount: 2

  service:
    type: ClusterIP

  ui:
    message: "Hello from GitOps"

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: podinfo.localhost
        paths:
          - path: /
            pathType: Prefix
